### ISSUE TITLE
How can we help?

### ISSUE THREAD

**Issue by lseelenbinder** [AlexPikalov/cdrs-async#1]
Hi Alex!

We're (@stadiamaps) using the synchronous variant of your CDRS crate in one of our Rust applications and we really like it. We're wrapping the sync operations in a Tokio `blocking` thread, so it's not ideal.

 How can we help push the `async` version along?

Looking forward to helping!

**Comment by AlexPikalov** [comment]
Hi @lseelenbinder ,

Sorry for a late replay. I need to think about the road map and some high-level architecture first. It looks for me as a good basis for a collaboration on such an early stage. If you have any thoughts feel free to share it here.

Will do my best to come up with something next week

**Comment by lseelenbinder** [comment]
Great, @AlexPikalov.

We're pretty experienced in Rust (async and sync), but rather inexperienced when it comes to Cassandra's protocol internals, if that helps you think about how we can assist.

Is it reasonable to directly port the sync crate to async primitives or do you believe rebuilding entirely would be best?

**Comment by AlexPikalov** [comment]
@lseelenbinder 
For my case it's pretty much opposite, I have very limited experience if it comes to async Rust.

I was thinking about creating some simplified version of CDRS, probably without load balancing support, without transport polymorphism and to include TCP transport only. I believed these simplifications will allow to quickly prototype the solution and verify some ideas. Later on this can be used as a foundation for some reacher client implementation.

So far, I was trying to think in API first fashion. I personally like a current query API from version 2 that is built on top of corresponded traits (I've kept them here https://github.com/AlexPikalov/cdrs-async/tree/master/src/query). With that being said, they can be revised in each moment and changed to something more developer-friendly if something like that comes up.

With APIs defined, we can try to evaluate different approaches. I was thinking about switching to async TCP streams and built some abstraction that would properly manage async tasks on top of the streams. What these abstraction could do is to register a task for a query frame in the moment of submission and return a Future that will be eventually resolved once a driver receives a response frame from a server.

Not sure if it makes sense because these are just my initial thoughts which I never verified practically.

Also I've extracted all that is related to Cassandra frames marshalling and unmarshalling into a separate crate https://github.com/AlexPikalov/cassandra-proto so that anybody could build its own driver that matches their needs. (Though it's not yet re-integrated into original CDRS code where it came from)

Apart of that I can provide any help related to Cassandra internals if it will help to make you the think faster here or in another repo.

**Comment by lseelenbinder** [comment]
> I was thinking about creating some simplified version of CDRS, probably without load balancing support, without transport polymorphism and to include TCP transport only. I believed these simplifications will allow to quickly prototype the solution and verify some ideas. Later on this can be used as a foundation for some reacher client implementation.

That sounds good to me. We would definitely want load balancing shortly afterwards, but this wouldn't be a blocker to us testing the crate.

> I personally like a current query API from version 2 that is built on top of corresponded traits (I've kept them here https://github.com/AlexPikalov/cdrs-async/tree/master/src/query).

I like them, too! Let's definitely maintain that interface.

> Not sure if it makes sense because these are just my initial thoughts which I never verified practically.

👍 

We're probably not going to have free cycles available until next month, so we have some time to hash out the best approach and way to split the workload.

**Comment by rw** [comment]
@AlexPikalov We'd also like to help! :-]

Would it be useful to look at the APIs of the [cpp-cassandra](https://crates.io/crates/cassandra-cpp) project? It supports async.

Edit: The [darkredis](https://crates.io/crates/darkredis) project may be a good model for you (perhaps moreso than cpp-cassandra, which uses a lot of unsafe Rust).

**Comment by lseelenbinder** [comment]
Cool, @rw! Let's do this. 👊

**Comment by AlexPikalov** [comment]
Hi guys,

Thanks for the examples and for you willingness to help! I'll check both of them. Hopefully, it will help to progress with cdrs async.

**Comment by rw** [comment]
I'm contacting the darkredis author about some of this, too.

**Comment by Bunogi** [comment]
Darkredis author here. I have some experience with asynchronous Rust, and I can answer any question about darkredis.

**Comment by rw** [comment]
I think a v0 that would be immediately useful (for me, at least 😃) would be an async library that can get and set keys with quorum consistency. Does that seem like a good minimum viable project?

**Comment by AlexPikalov** [comment]
@rw
What I could do relatively quickly is existing functionality without load balancing and connection pools. Consistency and other query parameters is something that is easy to keep.

As an update - I'm currently a bit struggling with how to implement in Rust async idiomatic way getting responses from single TcpStream and resolve corresponded response-futures. In other words, how to implement a demultiplexer. And if it's needed or there is an another way.

**Comment by rw** [comment]
@AlexPikalov That sounds great!

I have some initial thoughts on how to handle those callbacks, but they're just first impressions. If you suspend query tasks once their [StreamId](https://docs.datastax.com/en/developer/java-driver/2.1/manual/pooling/) is known, you'll probably put that information in a HashMap<StreamId, X> so that you can resume the task once the result comes back from Cassandra. I don't yet know what X would be, though. :-]

**Comment by AlexPikalov** [comment]
Some update from my side.

After some break I got back to the async version. In last commit I managed to make a first draft implementation of QueryExecutor trait that works as a demultiplexer which "resolves" a future assigned to a given StreamID.

I want to believe that from now on the development will go faster from my end. 🙂

**Comment by AlexPikalov** [comment]
Closing the issue.
